name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
      - deployment # TODO: remove this after testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '21' 

    - name: Install latest npm
      run: npm install -g npm@latest
    
    - name: Clear npm Cache
      run: npm cache verify

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
